<a href="https://colab.research.google.com/github/Lexxxi42/data-preprocessing/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Блок 1. NumPy и векторизованная обработка данных

In [ ]:
import numpy as np

## Задание 1.1. Базовые свойства массивов

> Вы анализируете данные о заказах интернет-магазина.



*   delivery_time - время доставки в минутах;
*   order_price - стоимость заказа в рублях;
*   items_count - количество товаров в заказе.





In [ ]:
delivery_time = np.array([35, 42, 28, 51, 39, 63, 31, 45])
order_price = np.array([1200, 3500, 800, 4200, 1900, 5600, 1500, 2800])
items_count = np.array([2, 5, 1, 7, 3, 8, 2, 4])

In [ ]:
def get_info(arr):
  return print(f'shape = {arr.shape}\nndim = {arr.ndim}\nsize = {arr.size}\n{'-'*10}')

print(f'INFO about delivery_time:')
get_info(delivery_time)

print(f'INFO about order_price:')
get_info(order_price)

print(f'INFO about items_count:')
get_info(items_count)

INFO about delivery_time:
shape = (8,)
ndim = 1
size = 8
----------
INFO about order_price:
shape = (8,)
ndim = 1
size = 8
----------
INFO about items_count:
shape = (8,)
ndim = 1
size = 8
----------


Что такое size

In [ ]:
len(delivery_time) == len(order_price) == len(items_count) # все три массива одинаковы по количеству наблюдений

True

Объясните, почему каждый индекс в трёх массивах должен соответствовать одному и
тому же заказу.

**Вопрос для анализа**

`Что произойдёт с результатами анализа, если delivery_time содержит 8 наблюдений, а
order_price — только 7? Почему это является проблемой не только с точки зрения
Python, но и с точки зрения качества данных?`

## Задание 1.2. Двумерные массивы

In [ ]:
orders = np.column_stack([delivery_time, order_price, items_count])
orders

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

In [ ]:
orders.shape

(8, 3)

In [ ]:
orders[0]

array([  35, 1200,    2])

In [ ]:
orders[:,0].sum()

np.int64(334)

In [ ]:
orders[:,1].sum()

np.int64(21500)

In [ ]:
orders[5][2]

np.int64(8)

In [ ]:
orders[2:,:2]

array([[  28,  800],
       [  51, 4200],
       [  39, 1900],
       [  63, 5600],
       [  31, 1500],
       [  45, 2800]])

In [ ]:
orders[:5]

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3]])

In [ ]:
orders[:,:2]

array([[  35, 1200],
       [  42, 3500],
       [  28,  800],
       [  51, 4200],
       [  39, 1900],
       [  63, 5600],
       [  31, 1500],
       [  45, 2800]])

**Вопрос для анализа**

`Объясните, почему:
orders.shape
возвращает (8, 3), а:
orders.size
возвращает 24.
Что характеризует каждый из этих показателей?`

## Задание 1.3. View и Copy

In [ ]:
delivery = orders[:, 0]
delivery

array([35, 42, 28, 51, 39, 63, 31, 45])

In [ ]:
delivery[0] += 1000
delivery

array([1035,   42,   28,   51,   39,   63,   31,   45])

In [ ]:
orders

array([[1035, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

`Объясните, почему изменение delivery повлияло на исходную матрицу.`

In [ ]:
orders = np.column_stack([delivery_time, order_price, items_count])
orders

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

In [ ]:
delivery_copy = orders[:, 0].copy()

In [ ]:
delivery_copy[0] += 1000
delivery_copy

array([1035,   42,   28,   51,   39,   63,   31,   45])

In [ ]:
orders

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

**Вопрос для анализа**

`Почему понимание различия между view и copy важно при обработке реальных наборов
данных?
Приведите пример ситуации, в которой случайное изменение view может привести к ошибке
в дальнейшем анализе.`

## Задание 1.4. Фильтрация с помощью булевых масок

In [ ]:
delivery_time_copy = np.array([35, 42, 28, 51, 39, 63, 31, 45]).copy()

In [ ]:
mask = delivery_time_copy >= 45
mask

array([False, False, False,  True, False,  True, False,  True])

In [ ]:
critical_delivery_time = delivery_time[mask]
critical_delivery_time

array([51, 63, 45])

In [ ]:
len(critical_delivery_time)

3

In [ ]:
critical_delivery_time.sum()/len(critical_delivery_time)

np.float64(53.0)

**Вопрос для анализа**

`В чём различие между условиями:
delivery_time > 45
и
delivery_time >= 45
Как изменение граничного условия может повлиять на бизнес-метрику?`

## Задание 1.5. Фильтрация по нескольким условиям

In [ ]:
mask = (order_price > 3000) & (items_count > 4)
mask

array([False,  True, False,  True, False,  True, False, False])

In [ ]:
richy = orders[mask]
richy

array([[  42, 3500,    5],
       [  51, 4200,    7],
       [  63, 5600,    8]])

In [ ]:
richy_cost = richy[:,1]
richy_cost

array([3500, 4200, 5600])

In [ ]:
richy_time = richy[:,0]
richy_time

array([42, 51, 63])

In [ ]:
richy_time.sum()/len(richy_time)

np.float64(52.0)

**Вопрос для анализа**

`Почему анализ комбинации нескольких признаков может дать более полезный результат для
бизнеса, чем анализ каждого признака отдельно?
Приведите пример ситуации, когда отдельный показатель выглядит нормально, но комбинация
нескольких признаков выявляет проблему.`

# Блок 2. Описательная статистика

## Задание 2.1. Влияние выбросов на статистические показатели

In [ ]:
delivery_time = np.array([8, 9, 10, 11, 12])

In [ ]:
np.mean(delivery_time)

np.float64(10.0)

In [ ]:
np.median(delivery_time)

np.float64(10.0)

In [ ]:
delivery_time_corrupted = np.append(delivery_time, 1000)

In [ ]:
np.mean(delivery_time_corrupted)

np.float64(175.0)

In [ ]:
np.median(delivery_time_corrupted)

np.float64(10.5)

**Вопросы для анализа**

`1. Почему среднее так сильно изменилось?
2. Почему медиана изменилась значительно меньше?
3. Какой показатель лучше описывает типичное время доставки при наличии редких
экстремальных значений?
4. Приведите пример, когда среднее значение является более информативным
показателем, чем медиана.`

## Задание 2.2. Процентили и SLA

In [1]:
np.random.seed(42)
delivery_simulated = np.random.normal(
 loc=30,
 scale=5,
 size=1000
)

NameError: name 'np' is not defined

## Задание 2.3. Разброс и предсказуемость

## Задание 2.4. Корреляция

## Задание 2.5. Корреляция и скрытые факторы

# Блок 3. Bootstrap и статистические гипотезы
## Задание 3.1. Bootstrap и доверительный интервал

## Задание 3.2. Формулировка гипотез и ошибки I и II рода

## Задание 3.3. p-value и принятие решения

# Итоговый вопрос лабораторной работы