<a href="https://colab.research.google.com/github/Lexxxi42/data-preprocessing/blob/main/%D0%9F%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Блок 1. NumPy и векторизованная обработка данных

In [3]:
import numpy as np

## Задание 1.1. Базовые свойства массивов

> Вы анализируете данные о заказах интернет-магазина.



*   delivery_time - время доставки в минутах;
*   order_price - стоимость заказа в рублях;
*   items_count - количество товаров в заказе.





In [4]:
delivery_time = np.array([35, 42, 28, 51, 39, 63, 31, 45])
order_price = np.array([1200, 3500, 800, 4200, 1900, 5600, 1500, 2800])
items_count = np.array([2, 5, 1, 7, 3, 8, 2, 4])

Выведем shape, ndim и size для каждого массива

In [40]:
def get_info(arr):
  return print(f'shape = {arr.shape}\nndim = {arr.ndim}\nsize = {arr.size}\n{'-'*10}\n')

print(f'Delivery_time:')
get_info(delivery_time)

print(f'Order_price:')
get_info(order_price)

print(f'Items_count:')
get_info(items_count)

Delivery_time:
shape = (5,)
ndim = 1
size = 5
----------

Order_price:
shape = (8,)
ndim = 1
size = 8
----------

Items_count:
shape = (8,)
ndim = 1
size = 8
----------



> Что такое size?



Проверим, что наблюдний в массивах одинаковое количество

In [6]:
len(delivery_time) == len(order_price) == len(items_count) # все три массива одинаковы по количеству наблюдений

True

> Объясните, почему каждый индекс в трёх массивах должен соответствовать одному и
тому же заказу.

**Вопрос для анализа**

`Что произойдёт с результатами анализа, если delivery_time содержит 8 наблюдений, а order_price — только 7? Почему это является проблемой не только с точки зрения Python, но и с точки зрения качества данных?`

## Задание 1.2. Двумерные массивы

Объединим данные в единую матрицу

In [7]:
orders = np.column_stack([delivery_time, order_price, items_count])
orders

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

Узнаем shape

In [8]:
orders.shape

(8, 3)

Данные первого заказа

In [9]:
orders[0]

array([  35, 1200,    2])

Время доставки всех заказов

In [10]:
orders[:,0].sum()

np.int64(334)

Стоимость всех заказов

In [11]:
orders[:,1].sum()

np.int64(21500)

Количество товаров в шестом заказе

In [12]:
orders[5][2]

np.int64(8)

С помощью срезов получим все заказы после третьего

In [13]:
orders[2:,:2]

array([[  28,  800],
       [  51, 4200],
       [  39, 1900],
       [  63, 5600],
       [  31, 1500],
       [  45, 2800]])

Первые пять заказов и первые два признака

In [14]:
orders[:5]

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3]])

In [15]:
orders[:,:2]

array([[  35, 1200],
       [  42, 3500],
       [  28,  800],
       [  51, 4200],
       [  39, 1900],
       [  63, 5600],
       [  31, 1500],
       [  45, 2800]])

**Вопрос для анализа**

`Объясните, почему:
orders.shape
возвращает (8, 3), а:
orders.size
возвращает 24.
Что характеризует каждый из этих показателей?`

## Задание 1.3. View и Copy

Выделим из матрицы orders данные о скорости доставки

In [16]:
delivery = orders[:, 0]
delivery

array([35, 42, 28, 51, 39, 63, 31, 45])

Изменим первый элемент на 1000

In [17]:
delivery[0] += 1000
delivery

array([1035,   42,   28,   51,   39,   63,   31,   45])

Проверим orders

In [18]:
orders

array([[1035, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

`Объясните, почему изменение delivery повлияло на исходную матрицу.`

Восстановим матрицу orders

In [19]:
orders = np.column_stack([delivery_time, order_price, items_count])
orders

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

Создадим независимую копию

In [20]:
delivery_copy = orders[:, 0].copy()

Изменим на 1000

In [21]:
delivery_copy[0] += 1000
delivery_copy

array([1035,   42,   28,   51,   39,   63,   31,   45])

Проверим orders

In [22]:
orders

array([[  35, 1200,    2],
       [  42, 3500,    5],
       [  28,  800,    1],
       [  51, 4200,    7],
       [  39, 1900,    3],
       [  63, 5600,    8],
       [  31, 1500,    2],
       [  45, 2800,    4]])

**Вопрос для анализа**

`Почему понимание различия между view и copy важно при обработке реальных наборов
данных?
Приведите пример ситуации, в которой случайное изменение view может привести к ошибке
в дальнейшем анализе.`

## Задание 1.4. Фильтрация с помощью булевых масок

In [23]:
delivery_time_copy = np.array([35, 42, 28, 51, 39, 63, 31, 45]).copy()

Создадим булеву маску для заказов, время доставки которых более 45 минут включительно

In [24]:
mask = delivery_time_copy >= 45
mask

array([False, False, False,  True, False,  True, False,  True])

Получим проблемные заказы по маске

In [25]:
critical_delivery_time = delivery_time[mask]
critical_delivery_time

array([51, 63, 45])

Количество заказов

In [26]:
len(critical_delivery_time)

3

Среднее время доставки

In [27]:
critical_delivery_time.sum()/len(critical_delivery_time)

np.float64(53.0)

**Вопрос для анализа**

`В чём различие между условиями:
delivery_time > 45
и
delivery_time >= 45
Как изменение граничного условия может повлиять на бизнес-метрику?`

## Задание 1.5. Фильтрация по нескольким условиям

Создадим булеву маску для заказов, стоимость которых более 3000 и с колчеством товаров более 4

In [28]:
mask = (order_price > 3000) & (items_count > 4)
mask

array([False,  True, False,  True, False,  True, False, False])

Получим матрицу

In [41]:
richy = orders[mask]
richy

array([[  42, 3500,    5],
       [  51, 4200,    7],
       [  63, 5600,    8]])

Стоимость каждого

In [30]:
richy_cost = richy[:,1]
richy_cost

array([3500, 4200, 5600])

Время доставки каждого

In [31]:
richy_time = richy[:,0]
richy_time

array([42, 51, 63])

Среднее время доставки

In [32]:
richy_time.sum()/len(richy_time)

np.float64(52.0)

**Вопрос для анализа**

`Почему анализ комбинации нескольких признаков может дать более полезный результат для
бизнеса, чем анализ каждого признака отдельно?
Приведите пример ситуации, когда отдельный показатель выглядит нормально, но комбинация
нескольких признаков выявляет проблему.`

# Блок 2. Описательная статистика

## Задание 2.1. Влияние выбросов на статистические показатели

Есть массив времени доставки заказов

In [33]:
delivery_time = np.array([8, 9, 10, 11, 12])

Среднее

In [42]:
first_mean = np.mean(delivery_time)
first_mean

np.float64(10.0)

Медиана

In [43]:
first_median = np.median(delivery_time)
first_median

np.float64(10.0)

Добавим еще наблюдение

In [45]:
delivery_time_corrupted = np.append(delivery_time, 1000)

Среднее

In [46]:
second_mean = np.mean(delivery_time_corrupted)
second_mean

np.float64(175.0)

Медиана

In [48]:
second_median = np.median(delivery_time_corrupted)
second_median

np.float64(10.5)

Сравним изменения

In [51]:
second_mean - first_mean

np.float64(165.0)

In [50]:
second_median - first_median

np.float64(0.5)

**Вопросы для анализа**

`1. Почему среднее так сильно изменилось?
2. Почему медиана изменилась значительно меньше?
3. Какой показатель лучше описывает типичное время доставки при наличии редких
экстремальных значений?
4. Приведите пример, когда среднее значение является более информативным
показателем, чем медиана.`

## Задание 2.2. Процентили и SLA

Интернет-магазин заявляет:

> Не менее 90% заказов доставляются за 40 минут или быстрее.
>
> Для проверки SLA смоделируйте 1000 наблюдений времени доставки.
>
> Используйте нормальное распределение со следующими параметрами:

• среднее — 30 минут;

• стандартное отклонение — 5 минут.

In [39]:
np.random.seed(42)
delivery_simulated = np.random.normal(
 loc=30,
 scale=5,
 size=1000
)

Среднее значение

Стандартное отклонение

Медиана

Рассчитаем процентили

**Вопросы для анализа**

1. Что означает p90 для времени доставки?
2. Что означает p95?
3. Почему для распределения времени доставки p95 обычно выше p90?
4. Что изменится в управлении логистикой, если компания начнёт ориентироваться не только на p90, но и на p95?

**Продуктовый вывод**

Сформулируйте вывод для менеджера продукта в 2–3 предложениях:

1. выполняется ли SLA;

2. насколько хорошо контролируется длинный хвост распределения.

## Задание 2.3. Разброс и предсказуемость

Две курьерские службы выполнили по пять одинаковых доставок.

In [39]:
service_A = np.array([28, 29, 30, 31, 32])
service_B = np.array([15, 20, 30, 40, 45])

Среднее

Медиана

Стандартное отклонение

90-й процентиль

**Вопросы для анализа**

1. Почему одинаковые или близкие средние значения не означают одинаковое качество работы?
2. Какая служба является более предсказуемой?
3. Какую службу вы выбрали бы для доставки дорогой электроники?
4. Какие статистические показатели повлияли бы на ваше решение?

## Задание 2.4. Корреляция

Предположим, что увеличение количества товаров в заказе может приводить к увеличению времени его обработки и доставки.

In [39]:
np.random.seed(42)
items = np.random.randint(1, 10, 100)
delivery_time_correlated = (
 20
 + 3 * items
 + np.random.normal(0, 3, 100)
)

Рассчитаем коэффициент корреляции Пирсона между items и delivery_time_correlated

Извлечем коэффициент r

Определим направление связи

Силу линейной связи

Сформулируйте возможное объяснение наблюдаемой зависимости с точки зрения
работы склада и доставки.

**Вопрос для анализа**

Можно ли на основании высокого значения корреляции утверждать:
«Увеличение количества товаров является причиной увеличения времени доставки»?
Объясните ответ.

## Задание 2.5. Корреляция и скрытые факторы

**Рассмотрим ситуацию:**

Летом одновременно увеличиваются:

• продажи мороженого;

• количество несчастных случаев на воде.

На основании этих данных аналитик делает вывод:

> «Продажа мороженого приводит к увеличению количества несчастных случаев на воде».

**Что необходимо сделать**
1. Объясните, почему высокая корреляция не доказывает наличие причинно-следственной
связи.
2. Определите фактор, который может влиять одновременно на оба показателя.
3. Объясните механизм возникновения наблюдаемой корреляции.
4. Приведите собственный пример ложной корреляции из бизнеса, технологий, медиа или
повседневной жизни.

# Блок 3. Bootstrap и статистические гипотезы
## Задание 3.1. Bootstrap и доверительный интервал

## Задание 3.2. Формулировка гипотез и ошибки I и II рода

## Задание 3.3. p-value и принятие решения

# Итоговый вопрос лабораторной работы